version: '3.3'
services:
  dictionary-etl:
    container_name: dictionaryetl
    build: .
    env_file: .env
    ports:
      - "8086:8086"
    networks:
      etlnetwork:
        ipv4_address: 172.20.0.2

networks:
  etlnetwork:
    driver: bridge
    config:
      - subnet: "172.20.0.0/16"
