version: '3.3'
services:
  dictionary-etl:
    container_name: dictionaryetl
    build: .
    env_file: .env
    ports:
      - "8086:8086"
    networks:
      - dictionaryetl

networks:
  dictionaryetl:
