version: '3.3'
services:
  dictionary-etl:
    container_name: dictionaryetl-ras
    build: .
    env_file: .env
    ports:
      - "8066:8066"
    networks:
      - dictionaryetl

networks:
  dictionaryetl:
