version: '3.3'

services:
  postgres-db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dictionary_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: