version: '3.3'

services:
  postgres-db:
    image: postgres:16.3
    container_name: postgres-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dictionary_db
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8g
    shm_size: 8g

volumes:
  postgres_data: