version: '3.3'
services:
  dictionary-etl:
    container_name: dictionaryetl
    build: .
    env_file: .env
    ports:
      - "8086:8086"
    networks:
      - dictionaryetl
      - etlnetwork

networks:
  dictionaryetl:
  etlnetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.20.0.2"
