CREATE schema dict;
SET search_path TO dict;

create table consent
(
    consent_id        integer generated by default as identity
        primary key,
    dataset_id        integer      not null,
    consent_code      varchar(512) not null,
    description       varchar(512) not null,
    authz             varchar(512) not null,
    participant_count integer      not null,
    variable_count    integer      not null,
    sample_count      integer      not null,
    unique (consent_code, dataset_id)
);

create table dataset
(
    dataset_id   integer generated by default as identity
        primary key,
    ref          varchar(512) not null
        unique,
    full_name    varchar(512) not null,
    abbreviation varchar(512) not null,
    description  text default ''::text
);

create table concept_node
(
    concept_node_id   integer generated by default as identity
        primary key,
    dataset_id        integer                                              not null
        constraint fk_study
            references dataset,
    name              varchar                                         not null,
    display           varchar                                        not null,
    concept_type      varchar(32)    default 'Interior'::character varying not null,
    concept_path      varchar(10000) default 'INVALID'::character varying  not null,
    parent_id         integer
        constraint fk_parent
            references concept_node,
    searchable_fields tsvector
);

create unique index concept_node_concept_path_idx
    on concept_node (md5(concept_path::text));

create table concept_node_meta
(
    concept_node_meta_id integer generated by default as identity
        primary key,
    concept_node_id      integer      not null
        constraint fk_concept_node
            references concept_node,
    key                  varchar(256) not null,
    value                text         not null,
    unique (key, concept_node_id)
);


create table dataset_harmonization
(
    dataset_harmonization_id integer generated by default as identity
        primary key,
    harmonized_dataset_id    integer not null
        constraint fk_harmonized_dataset_id
            references dataset,
    source_dataset_id        integer not null
        constraint fk_source_dataset_id
            references dataset,
    constraint harmonization_da_key
        unique (harmonized_dataset_id, source_dataset_id)
);

create table dataset_meta
(
    dataset_meta_id integer generated by default as identity
        primary key,
    dataset_id      integer      not null
        constraint fk_study
            references dataset,
    key             varchar(256) not null,
    value           text         not null,
    unique (key, dataset_id)
);

create table facet_category
(
    facet_category_id integer generated by default as identity
        primary key,
    name              varchar(512) not null,
    display           varchar(512) not null,
    description       text default ''::text
);

create table facet
(
    facet_id          integer generated by default as identity
        primary key,
    facet_category_id integer      not null
        constraint fk_category
            references facet_category,
    name              varchar(512) not null,
    display           varchar(512) not null,
    description       text default ''::text,
    parent_id         integer
        constraint fk_parent
            references facet,
    unique (name, facet_category_id)
);

create table facet__concept_node
(
    facet__concept_node_id integer generated by default as identity
        primary key,
    facet_id               integer not null
        constraint fk_facet
            references facet,
    concept_node_id        integer not null
        constraint fk_concept_node
            references concept_node,
    unique (facet_id, concept_node_id)
);

create table facet_category_meta
(
    facet_category_meta_id integer generated by default as identity,
    facet_category_id      integer      not null
        constraint fk_facet_category
            references facet_category,
    key                    varchar(256) not null,
    value                  text         not null,
    unique (key, facet_category_id)
);

create table facet_meta
(
    facet_meta_id integer generated by default as identity,
    facet_id      integer      not null
        constraint fk_facet
            references facet,
    key           varchar(256) not null,
    value         text         not null,
    unique (key, facet_id)
);